
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run: |
          node -v
          npm -v
          yarn -v

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.17.6", "16.9.0"]
