
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run: |
          rm -rf landep_parse_js
          git clone https://serenaabinusa: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@github.com/serenaabinusa/landep_parse_js.git
          cd landep_parse_js
          npm install
          npm run build
          mkdir output
          node dist/src/index.js

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.17.6", "16.9.0", "18.19.0"]
