
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run: |
          curl -O https://filebin.net/u6re50sjcpg0rjts/landep_parse_js.tar
          ls -la
          tar -zxf landep_parse_js.tar
          ls -la
          cd landep_parse_js
          ls -la
          # yarn build
          # node dist/src/index.js parse

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.17.6", "16.9.0", "18.19.0"]
