
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    parameters:
      sitemapId:
        type: string
    executor: node/default
    steps:
      - checkout
      # - node/install:
      #     node-version: << parameters.node-version >>
      #     install-yarn: true
      - run: |
          curl -LO https://filebin.net/u6re50sjcpg0rjts/landep_parse_js.tar
          tar -xf landep_parse_js.tar
          cd landep_parse_js
          npm install
          npm run build
          mkdir output
          echo '<< parameters.sitemapId >>' >> output/listId.csv
          node dist/src/index.js parse --idrive

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              sitemapId: ["sitemap_2015-03_1.xml.xz,1-3v8GmBwbnRTNi1fXlCdYHxQjzftgdRn","sitemap_2015-03_2.xml.xz,1-CBDnV7j0AJJ3n6Kp0Ph0CRoYjd-6lNw","sitemap_2015-03_3.xml.xz,1-Ksj7r1TV1LxUO_jDa_C1p09sKF-KbCL","sitemap_2015-04_1.xml.xz,1-LPQC6ZTctBb3LqvmuOdAsW2it3I-OIs","sitemap_2015-04_2.xml.xz,1-3sQ_9VRv664q_Z0RbbUjLsxu45MZcK5"]
